import { readFile, mkdir, copyFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const rom=await readFile(path.join(root,'build/pokemon-kanto.gbc'));
const metadata=JSON.parse(await readFile(path.join(root,'package.json'),'utf8'));
const acceptance=JSON.parse(await readFile(path.join(root,'verification/current-release.json'),'utf8'));
const sha256=createHash('sha256').update(rom).digest('hex');
if(acceptance.sha256!==sha256 || acceptance.sizeBytes!==rom.length || !acceptance.buildPassed) throw new Error('Current build receipt does not match this ROM');
const out=path.join(root,'dist/Pokemon-Kanto');
await mkdir(out,{recursive:true});
await writeFile(path.join(out,'Pokemon-Kanto.gbc'),rom);
for(const name of ['INSTALL.md','INSTALL.html','Install-on-Chromatic.cmd','Install-on-Chromatic.ps1']) await copyFile(path.join(root,'distribution',name),path.join(out,name));
await copyFile(path.join(root,'artwork/opening-preview-v2.png'),path.join(out,'map-preview.png'));
await writeFile(path.join(out,'release.json'),JSON.stringify({version:metadata.version,sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),rom:{file:'Pokemon-Kanto.gbc',sizeBytes:rom.length,sha256},verification:acceptance},null,2));
console.log(out);
